-- Authentication System Database Setup
-- This script creates the users table for the authentication system

-- Create users table
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'staff') NOT NULL DEFAULT 'staff',
  `fullName` VARCHAR(255) DEFAULT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `lastLogin` DATETIME DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_email` (`email`),
  INDEX `idx_role` (`role`),
  INDEX `idx_isActive` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default admin user (password: admin123)
-- Password hash is generated using bcryptjs with salt rounds = 10
INSERT INTO `users` (`email`, `password`, `role`, `fullName`, `isActive`, `createdAt`, `updatedAt`) 
VALUES (
  'admin@jewellery.com',
  '$2a$10$YourHashedPasswordHere',
  'admin',
  'System Administrator',
  TRUE,
  NOW(),
  NOW()
) ON DUPLICATE KEY UPDATE `email` = `email`;

-- Note: The actual password hash will be generated by the setup-admin.js script
-- This is just a placeholder. Run: npm run setup-admin
